version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          command: bash .circleci/deploy.sh
